16:36:06.389 [main] ERROR o.prgrms.kdt.JdbcCustomerRepository - Got an error while closing connection
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.prgrms.kdt.JdbcCustomerRepository.deleteAllCustomers(JdbcCustomerRepository.java:132)
	at org.prgrms.kdt.JdbcCustomerRepository.main(JdbcCustomerRepository.java:151)
16:36:06.397 [main] INFO  o.prgrms.kdt.JdbcCustomerRepository - deleted count -> 0 
16:36:06.402 [main] INFO  o.prgrms.kdt.JdbcCustomerRepository - created customerId -> 69a5662a-7b4f-4453-a913-0ea82bdf80ca
16:36:06.402 [main] INFO  o.prgrms.kdt.JdbcCustomerRepository - created UUID Version -> 4
16:36:06.450 [main] ERROR o.prgrms.kdt.JdbcCustomerRepository - Got an error while closing connection
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.prgrms.kdt.JdbcCustomerRepository.insertCustomer(JdbcCustomerRepository.java:99)
	at org.prgrms.kdt.JdbcCustomerRepository.main(JdbcCustomerRepository.java:157)
16:36:06.492 [main] ERROR o.prgrms.kdt.JdbcCustomerRepository - Got an error while closing connection
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.prgrms.kdt.JdbcCustomerRepository.findAllIds(JdbcCustomerRepository.java:78)
	at org.prgrms.kdt.JdbcCustomerRepository.main(JdbcCustomerRepository.java:158)
